// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main(head_only)
{
	if(!IsDefined(head_only))
	{
		head_only = false;
	}

	self.headModel = "c_rus_nikolai_dlc5_head";
	self attach(self.headModel, "", true);

	if(head_only)
	{
		return;
	}

	self setModel("c_rus_nikolai_dlc5_body");
	self.voice = "russian";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_rus_nikolai_dlc5_body");
	precacheModel("c_rus_nikolai_dlc5_head");
}
