// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("t4_char_usa_marine_player_body2_1");
	self.headModel = "t4_char_usa_marine_head_2_2";
	self attach(self.headModel, "", true);
	self.hatModel = "t4_char_usa_raider_helm2";
	self attach(self.hatModel);	
	self.voice = "russian";
	self.skeleton = "base";
}

precache()
{
	precacheModel("t4_char_usa_marine_player_body2_1");
	precacheModel("t4_char_usa_marine_head_2_2");
	precacheModel("t4_char_usa_raider_helm2");	
}
