// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("t4_char_usa_marine_player_body1_1");
	self.headModel = "t4_char_usa_marine_head_1_1";
	self attach(self.headModel, "", true);
	self.hatModel = "t4_char_usa_raider_helm1";
	self attach(self.hatModel);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("t4_char_usa_marine_player_body1_1");
	precacheModel("t4_char_usa_marine_head_1_1");
	precacheModel("t4_char_usa_raider_helm1");	
}
